version: 2

models:
  - name: genetic_findings
    description: "Consolidated view of genetic findings with related characteristics and ingredients"
    columns:
      - name: rsid
        description: "Reference SNP ID"
        tests:
          - not_null
      - name: gene
        description: "Gene name"
        tests:
          - not_null
      - name: risk_allele
        description: "Risk allele"
        tests:
          - not_null
      - name: effect
        description: "Effect description"
      - name: evidence_strength
        description: "Strength of evidence"
      - name: category
        description: "Category of the SNP"
        tests:
          - not_null
      - name: characteristics
        description: "Array of related skin characteristics"
      - name: beneficial_ingredients
        description: "Array of beneficial ingredients"
      - name: caution_ingredients
        description: "Array of ingredients to avoid or use with caution"