version: 2

models:
  - name: snp
    description: "SNP (Single Nucleotide Polymorphism) data"
    columns:
      - name: snp_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: rsid
        description: "Reference SNP ID"
        tests:
          - not_null
      - name: gene
        description: "Gene name"
        tests:
          - not_null
      - name: risk_allele
        description: "Risk allele"
        tests:
          - not_null
      - name: effect
        description: "Effect description"
      - name: evidence_strength
        description: "Strength of evidence"
      - name: category
        description: "Category of the SNP"
        tests:
          - not_null

  - name: skin_characteristic
    description: "Skin characteristics that can be influenced by genetic factors"
    columns:
      - name: characteristic_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Characteristic name"
        tests:
          - unique
          - not_null
      - name: description
        description: "Detailed description"
      - name: measurement_method
        description: "Method for measuring this characteristic"

  - name: skin_condition
    description: "Skin conditions related to genetic characteristics"
    columns:
      - name: condition_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Condition name"
        tests:
          - unique
          - not_null
      - name: description
        description: "Detailed description"
      - name: severity_scale
        description: "Scale for measuring severity"

  - name: ingredient
    description: "Beneficial ingredients for skin conditions"
    columns:
      - name: ingredient_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Ingredient name"
        tests:
          - unique
          - not_null
      - name: mechanism
        description: "Mechanism of action"
      - name: evidence_level
        description: "Level of scientific evidence"
      - name: contraindications
        description: "Known contraindications"

  - name: ingredient_caution
    description: "Ingredients to avoid based on genetic profile"
    columns:
      - name: caution_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: ingredient_name
        description: "Name of the ingredient"
        tests:
          - not_null
      - name: category
        description: "Category (Avoid or Use with Caution)"
        tests:
          - not_null
      - name: risk_mechanism
        description: "Mechanism of risk"
      - name: affected_characteristic
        description: "Affected skin characteristic"
      - name: alternative_ingredients
        description: "Alternative ingredients to use instead"