version: 2

sources:
  - name: raw
    database: "{{ env_var('DB_NAME', 'zando') }}"
    schema: public
    tables:
      - name: snp
        description: "Genetic variants with their associated genes, risk alleles, and effects"
        columns:
          - name: snp_id
            description: "Primary key"
          - name: rsid
            description: "Reference SNP ID"
          - name: gene
            description: "Gene name"
          - name: risk_allele
            description: "Risk allele"
          - name: effect
            description: "Effect description"
          - name: evidence_strength
            description: "Strength of evidence"
          - name: category
            description: "Category of the SNP"
      
      - name: skincharacteristic
        description: "Skin characteristics that can be influenced by genetic factors"
        columns:
          - name: characteristic_id
            description: "Primary key"
          - name: name
            description: "Characteristic name"
          - name: description
            description: "Detailed description"
          - name: measurement_method
            description: "Method for measuring this characteristic"
      
      - name: skincondition
        description: "Skin conditions related to genetic characteristics"
        columns:
          - name: condition_id
            description: "Primary key"
          - name: name
            description: "Condition name"
          - name: description
            description: "Detailed description"
          - name: severity_scale
            description: "Scale for measuring severity"
      
      - name: ingredient
        description: "Beneficial ingredients for skin conditions"
        columns:
          - name: ingredient_id
            description: "Primary key"
          - name: name
            description: "Ingredient name"
          - name: mechanism
            description: "Mechanism of action"
          - name: evidence_level
            description: "Level of scientific evidence"
          - name: contraindications
            description: "Known contraindications"
      
      - name: ingredientcaution
        description: "Ingredients to avoid based on genetic profile"
        columns:
          - name: caution_id
            description: "Primary key"
          - name: ingredient_name
            description: "Name of the ingredient"
          - name: category
            description: "Category (Avoid or Use with Caution)"
          - name: risk_mechanism
            description: "Mechanism of risk"
          - name: affected_characteristic
            description: "Affected skin characteristic"
          - name: alternative_ingredients
            description: "Alternative ingredients to use instead"
      
      - name: snp_characteristic_link
        description: "Association between SNPs and skin characteristics"
        columns:
          - name: snp_id
            description: "Foreign key to snp"
          - name: characteristic_id
            description: "Foreign key to skincharacteristic"
          - name: effect_direction
            description: "Direction of the effect"
          - name: evidence_strength
            description: "Strength of evidence"
      
      - name: characteristic_condition_link
        description: "Association between skin characteristics and conditions"
        columns:
          - name: characteristic_id
            description: "Foreign key to skincharacteristic"
          - name: condition_id
            description: "Foreign key to skincondition"
          - name: relationship_type
            description: "Type of relationship"
      
      - name: condition_ingredient_link
        description: "Association between skin conditions and recommended ingredients"
        columns:
          - name: condition_id
            description: "Foreign key to skincondition"
          - name: ingredient_id
            description: "Foreign key to ingredient"
          - name: recommendation_strength
            description: "Strength of recommendation"
          - name: guidance_notes
            description: "Usage guidance notes"
      
      - name: snp_ingredient_link
        description: "Association between SNPs and beneficial ingredients"
        columns:
          - name: snp_id
            description: "Foreign key to snp"
          - name: ingredient_id
            description: "Foreign key to ingredient"
          - name: benefit_mechanism
            description: "Mechanism of benefit"
          - name: recommendation_strength
            description: "Strength of recommendation"
          - name: evidence_level
            description: "Level of scientific evidence"
      
      - name: snp_ingredientcaution_link
        description: "Association between SNPs and ingredients to avoid"
        columns:
          - name: snp_id
            description: "Foreign key to snp"
          - name: caution_id
            description: "Foreign key to ingredientcaution"
          - name: evidence_level
            description: "Level of scientific evidence"
          - name: notes
            description: "Additional notes"