name: 'zando'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zando'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"

# Configuring models
models:
  zando:
    # Core models (staging or source models)
    core:
      +materialized: table
      +schema: core
    
    # Marts models (combined models for analysis)
    marts:
      +materialized: table
      +schema: marts

seeds:
  zando:
    +schema: seed_data

vars:
  # Variable for controlling which environment we're in
  environment: 'development'